### ISSUE TITLE
[404]: /engine/install/index.md

### ISSUE THREAD

**Issue by yaseenaljamal** [docker/docs#17997]
### Location

https://docs.docker.com/get-docker/

### Broken link

https://docs.docker.com/engine/install/index.md

### Comment

$ gh actions-importer configure
? Enter value for 'GITHUB_ACCESS_TOKEN' (leave empty to skip): 
...
```[tasklist]
### Tasks
- [ ] https://github.com/docker/docs/pull/17458
- [ ] https://github.com/docker/docs/pull/17624
- [ ] https://github.com/docker/docs/pull/17407
```

**Comment by thaJeztah** [comment]
Thanks for reporting!

@dvdksn it looks like links in the "note" are not converted from markdown (`/engine/install/index.md`) to "proper" links (`/engine/install/`).

It's also possible that the `index.md` is the culprit here (I recall some issues in the past with Hugo treating those slightly different in some cases);

<img width="808" alt="Screenshot 2023-08-23 at 10 06 54" src="https://github.com/docker/docs/assets/1804568/53e54dda-05ca-47ba-b340-8c98ffa2b630">

**Comment by dvdksn** [comment]
thanks @yaseenaljamal - yeah this is fixed in 91c178cbe1fcedf6442b3d78ba7b235c53b89559 - I just started the publish workflow

**Comment by dvdksn** [comment]
the `index.md` files are `_index.md` in Hugo (for list pages, i.e. section overviews. You can still have `index.md` for single pages with no children.)

**Comment by thaJeztah** [comment]
Ah! Thanks
