### ISSUE TITLE
Python-JAVA-AI-sudo

### ISSUE THREAD

**Issue by NanoSudoers** [docker/docs#20523]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

5555

### Location

https://docs.docker.com/reference/cli/dockerd/

```[tasklist]
### Tasks
- [ ] https://github.com/docker/docs/pull/20545
- [ ] https://github.com/docker/docs/pull/20556
- [ ] https://github.com/docker/docs/pull/20558
- [ ] https://github.com/docker/docs/issues/20549
```

```[tasklist]
### Tasks
- [ ] https://github.com/docker/docs/pull/19881
- [ ] https://github.com/docker/docs/pull/20557
- [ ] https://github.com/docker/docs/pull/20551
- [ ] https://github.com/docker/docs/pull/20558
- [ ] https://github.com/docker/docs/issues/20549
```
